services:
  nginx:
    container_name: nginx-aca
    image: nginx:aca
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    networks:
      - front-end
    ports:
      - 8081:8081

networks:
  front-end:
